package com.application.khaokhana.api;

public enum APIType {
    SIGN_IN,
    FOOD_LIST,
    USER_PROFILE,
    ADD_FOOD,
    ADD_PHOTO,

    FOOD_LIST_VENDOR,
    PAYMENT,
    USER_ORDER_LIST,
    FOOD_DELETE,
    REQUEST_ORDER_LIST,
    FOOD_EDIT,
    ORDER_CANCEL,
    ORDER_ACCEPT,
    ORDER_COMPLETE,
    UPDATE_FOOD,
    TRANSACTION_LIST,
    ORDER_DETAIL,

    FORGOT_API,
    VENDOR_LIST
}
